### ISSUE TITLE
text field clean is not working

### ISSUE THREAD

**Issue by divyang159** [Mindinventory/drop_down_list#11]
https://user-images.githubusercontent.com/55906611/221872896-6e269204-d8d0-4901-96e4-788608cf9235.mp4
`  void onClearTap() {
    widget.onTextChanged("");
    _editingController.clear();
  }`
  
  pls add the above code there I try but did not have access to create a branch.

**Comment by sahilmind** [comment]
@divyang159  I have updated the above code snippet in **`drop_down_list: 0.0.5`** please have a look.
I am happy to help you if required.
Thanks!
