### ISSUE TITLE
Why make this dynamic?

### ISSUE THREAD

**Issue by mcorrigan** [Mindinventory/drop_down_list#12]
https://github.com/Mindinventory/drop_down_list/blob/c5ca5ce2dd0a2f10d2f5b4ed1e98b1a44ea6f3fa/lib/src/drop_down.dart#L124

Seems like it would be cleaner to keep it typed like the list these are coming from. Is there something I'm missing?

**Comment by sahilmind** [comment]
@mcorrigan Thanks for the suggestion I have updated `selectedNameList` from `dynamic` to  `SelectedListItem` in **`drop_down_list: 0.0.5`** please have a look.
I am happy to help you if required.
Thanks!

**Comment by mcorrigan** [comment]
Hey awesome! I forked and changed it on my end, I just found it odd that it wasn't typed and wondered if there was something I needed to learn about in dart. 👍
