### ISSUE TITLE
Search hint text has an offset when not selected

### ISSUE THREAD

**Issue by romatallinn** [Mindinventory/drop_down_list#14]
When not selected, the search hint text is shifted toward the upper border.
When selected, however, it is aligned in the center, as meant to be.

iPhone 11 (iOS 16.0)

<img src="https://github.com/Mindinventory/drop_down_list/assets/14923964/adf3401b-17f5-483b-8651-c624049faaad" data-canonical-src="https://github.com/Mindinventory/drop_down_list/assets/14923964/adf3401b-17f5-483b-8651-c624049faaad" width="300" />
<img src="https://github.com/Mindinventory/drop_down_list/assets/14923964/50824990-be7a-430c-8342-42a731deae60" data-canonical-src="https://github.com/Mindinventory/drop_down_list/assets/14923964/50824990-be7a-430c-8342-42a731deae60" width="300" />

**Comment by ScottishRoss** [comment]
I found it to be the opposite. When unfocused it's correct, when focused it's offset. 
<img width="357" alt="Screenshot 2023-06-06 at 17 09 09" src="https://github.com/Mindinventory/drop_down_list/assets/25175556/76a14346-b8aa-4da1-9e6a-c7fac85806cc">

Did you find a solution to this?

**Comment by mi-raj04** [comment]
@romatallinn  solve this issue in https://pub.dev/packages/drop_down_list/versions
