### ISSUE TITLE
Search breaks listItemBuilder

### ISSUE THREAD

**Issue by romatallinn** [Mindinventory/drop_down_list#16]
Search outputs the sublist of the items. This means that indexes from the original list are no longer aligned with this sublist. So when I search, it outputs, for example, a match with one item that is being built by index 0. And there is no way for me to actually know what this item is. It should at least pass over `SelectedListItem` in `listItemBuilder` instead of index, so I can match it by value in the original list.

**Comment by jaydeepkaria-mi** [comment]
We have updated it in the latest version. Please check it. As of now closing this issue.

**Comment by romatallinn** [comment]
I don't see anything in v0.0.6 that would be a fix for the issue. But maybe I'm missing something? In this case, would appreciate a hint where to look.

Moreover, CHANGELOG says that v0.0.6 fixes #14, #18, #15, #13. This is #16, so maybe @jaydeepkaria-mi you closed it by mistake?

**Comment by romatallinn** [comment]
@jaydeepkaria-mi please reopen

**Comment by romatallinn** [comment]
@jaydeepkaria-mi any updates?
