### ISSUE TITLE
Setting background color

### ISSUE THREAD

**Issue by Dubemtopsite** [Mindinventory/drop_down_list#18]
![image](https://github.com/Mindinventory/drop_down_list/assets/31639636/c059a66e-4b21-4303-839a-c7f601fb1b14)

![image](https://github.com/Mindinventory/drop_down_list/assets/31639636/d5e20622-3008-49d6-92c7-da08aea49cb6)

From the image above when I switch to dark mode the top remain white color. What do I have to set to make it turn to the dark mode background color

**Comment by mi-raj04** [comment]
@Dubemtopsite solve this issue in [drop_down_list](https://pub.dev/packages/drop_down_list/versions)
