### ISSUE TITLE
How to limit the number of items selected with multiple selection?

### ISSUE THREAD

**Issue by sergiocelis-aite** [Mindinventory/drop_down_list#19]
I am using the package with the enableMultipleSelection: true option, but I want to limit the selection to a maximum of 5 items from my list. How can I do this?

**Comment by abrarmalekji345** [comment]
@sergiocelis-aite limiting selection is not available at the moment, if you have implemented this please create PR. thanks.

**Comment by abrarmalekji345** [comment]
@sergiocelis-aite Done, please update to 0.0.7
