### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by Paul-cbt** [Mindinventory/drop_down_list#2]
Hi, how is the background color selected by your package? 
Thanks

**Comment by Pm-explorer** [comment]
It is default color now. Let me know if you have different context for question @Paul-cbt

**Comment by deep-mindinventory** [comment]
@Paul-cbt can you please elaborate more on this point? Are you talking about the provision for changing the background color or something else?

**Comment by sahilmind** [comment]
@Paul-cbt Now you can change the background color of dropdown by adding `dropDownBackgroundColor` argument in `drop_down_list: 0.0.3` please have a look.
I am happy to help you if required.
Thanks!
