### ISSUE TITLE
error overflowing RenderFlex has an orientation of Axis.vertical

### ISSUE THREAD

**Issue by StillGC** [Mindinventory/drop_down_list#28]
I have an error when closing the search engine by closing it with the gesture of sliding the finger down

![image](https://github.com/user-attachments/assets/dfbe822a-cfc8-4c71-8448-65715e7f1418)

DETAILS
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.
The specific RenderFlex in question is: RenderFlex#dfe04 relayoutBoundary=up10 OVERFLOWING

**Comment by mohit-chauhan-mi** [comment]
@StillGC Please check this with the latest [version](https://pub.dev/packages/drop_down_list). Thanks.
