### ISSUE TITLE
best way to search objects with this package ?

### ISSUE THREAD

**Issue by thorizer** [Mindinventory/drop_down_list#4]
can this package handle searching objects ?
for example dropdown_search package have this 
```
DropdownSearch<UserModel>(
    itemAsString: (UserModel u) => u.userAsStringById(),
    onChanged: (UserModel? data) => print(data),
    dropdownSearchDecoration: InputDecoration(labelText: "User by id"),
)
```
I have a list of items that can have duplicate names, i want the value to be the id and the label to be the name
best DropDown in pubDev, only lacks searching through objects

**Comment by deep-mindinventory** [comment]
@thorizer please check latest version where we have added object with `name` and `value` which fulfilled for duplicate name.  It is also returning object on selection.
