### ISSUE TITLE
Change hintText

### ISSUE THREAD

**Issue by maiconkf** [Mindinventory/drop_down_list#7]
Can you please add a parameter to change the hintText?
I need to translate this text...

And I know about searchWidget but it's not possible to add padding... I only need to change the placeholder.

**Comment by lbarria77** [comment]
How can i chance the color text from the listo, i can see My options because the color is a light grey tone.  Also can i chance the hint text from the search and the color?

**Comment by sahilmind** [comment]
> How can i chance the color text from the list,

@lbarria77 you can use the `ListItemBuilder` and `searchWidget` to create a custom view as per your requirement by using **`drop_down_list: 0.0.5`** please have a look.
I am happy to help you if required.
Thanks!

**Comment by sahilmind** [comment]
@maiconkf As per your requirement, I have added the `searchHintText` property which helps to update the hint in **`drop_down_list: 0.0.5`** please have a look.
I am happy to help you if required.
Thanks!
