### ISSUE TITLE
No dismissible sheet

### ISSUE THREAD

**Issue by sergiocelis-aite** [Mindinventory/drop_down_list#8]
I would like to have an option to prevent the user from closing the list by tapping out. To be able to have control and that it closes only when the Done button is given

**Comment by sahilmind** [comment]
@sergiocelis-aite I have added the flag `isDismissible`, so it helps whether the bottom sheet will be dismissed when the user taps on the scrim and also added `BottomSheetListener` to know if the bottom sheet is collapsed or expanded by using the `extent` property.  in **`drop_down_list: 0.0.5 `** please have a look.
I am happy to help you if required.
Thanks!
