### ISSUE TITLE
Floating Menu instead of Bottom Sheet for Web

### ISSUE THREAD

**Issue by aytunch** [Mindinventory/drop_down_list#9]
In mobile, it makes sense to have a bottom sheet as the open menu container.
However in web, it would make more sense to display the opened menu under the item we tap (like a standart dropdown)
Can we do this? what would the strategy be? I would be glad to contribute if I can be headed towards the right direction
Thanks

**Comment by deep-mindinventory** [comment]
@aytunch Sure, you can contribute to the same and do the PR. Our thought behind this lib for the bottom sheet. You can use overlay and manage it via offset or other best practices.
